baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'For myself in two weeks'

[taxonomies]
    tag = "tags"
    category = "categories"

[markup.goldmark.renderer]
    unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  # BookTheme = 'light'
    BookTheme = 'dark'

